// Code generated by "versiongen"; DO NOT EDIT.
package schema

import (
	"github.com/hashicorp/go-version"
)

var (
	OldestAvailableVersion = version.Must(version.NewVersion("0.12.0"))
	LatestAvailableVersion = version.Must(version.NewVersion("1.9.1"))

	tofuVersions = version.Collection{
		version.Must(version.NewVersion("1.10.0-alpha2")),
		version.Must(version.NewVersion("1.10.0-alpha1")),
		version.Must(version.NewVersion("1.9.1")),
		version.Must(version.NewVersion("1.9.0")),
		version.Must(version.NewVersion("1.9.0-rc2")),
		version.Must(version.NewVersion("1.9.0-rc1")),
		version.Must(version.NewVersion("1.9.0-beta2")),
		version.Must(version.NewVersion("1.9.0-beta1")),
		version.Must(version.NewVersion("1.9.0-alpha2")),
		version.Must(version.NewVersion("1.9.0-alpha1")),
		version.Must(version.NewVersion("1.8.9")),
		version.Must(version.NewVersion("1.8.8")),
		version.Must(version.NewVersion("1.8.7")),
		version.Must(version.NewVersion("1.8.6")),
		version.Must(version.NewVersion("1.8.5")),
		version.Must(version.NewVersion("1.8.4")),
		version.Must(version.NewVersion("1.8.3")),
		version.Must(version.NewVersion("1.8.2")),
		version.Must(version.NewVersion("1.8.1")),
		version.Must(version.NewVersion("1.8.0")),
		version.Must(version.NewVersion("1.8.0-rc1")),
		version.Must(version.NewVersion("1.8.0-beta2")),
		version.Must(version.NewVersion("1.8.0-beta1")),
		version.Must(version.NewVersion("1.8.0-alpha1")),
		version.Must(version.NewVersion("1.7.8")),
		version.Must(version.NewVersion("1.7.7")),
		version.Must(version.NewVersion("1.7.6")),
		version.Must(version.NewVersion("1.7.5")),
		version.Must(version.NewVersion("1.7.4")),
		version.Must(version.NewVersion("1.7.3")),
		version.Must(version.NewVersion("1.7.2")),
		version.Must(version.NewVersion("1.7.1")),
		version.Must(version.NewVersion("1.7.0")),
		version.Must(version.NewVersion("1.7.0-rc1")),
		version.Must(version.NewVersion("1.7.0-beta1")),
		version.Must(version.NewVersion("1.7.0-alpha1")),
		version.Must(version.NewVersion("1.6.3")),
		version.Must(version.NewVersion("1.6.2")),
		version.Must(version.NewVersion("1.6.1")),
		version.Must(version.NewVersion("1.6.0")),
		version.Must(version.NewVersion("1.6.0-rc1")),
		version.Must(version.NewVersion("1.6.0-beta5")),
		version.Must(version.NewVersion("1.6.0-beta4")),
		version.Must(version.NewVersion("1.6.0-beta3")),
		version.Must(version.NewVersion("1.6.0-beta2")),
		version.Must(version.NewVersion("1.6.0-beta1")),
		version.Must(version.NewVersion("1.6.0-alpha5")),
		version.Must(version.NewVersion("1.6.0-alpha4")),
		version.Must(version.NewVersion("1.6.0-alpha3")),
		version.Must(version.NewVersion("1.6.0-alpha2")),
		version.Must(version.NewVersion("1.6.0-alpha1")),
	}
)
